settings: # realize start(init) で生成される
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
- name: app
  path: .
  commands:
    run:
      status: true
  args:
    - app
  watcher:
    paths:
    - /
    extensions:
    - go
    - yaml
